/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BACKUP_RESTORE;

import design.DataBaseHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class BACKUPAUTO extends javax.swing.JFrame {
    private int solanBackUp = 200;
    /**
     * Creates new form BACKUPAUTO
     */
    public BACKUPAUTO() {
        initComponents();
        jDateNgayBatDau.setDate(date);
        jDateNgayBatDauMoiNgay.setDate(date);
        jDatengayKetThucMoiNgay.setDate(date);
        
        jLabelGioKetthuc.setEnabled(false);
        txtGioKetThuc.setEnabled(false);
        cbCachKhoang.setEnabled(false);
        txtKhoang.setEnabled(false);
        
        if(radioMotNgay.isSelected())
        {
            jPanelMotLan.setVisible(true);
            jPanelNhieuNgay.setVisible(false);
        }
            
        else
        {
           jPanelMotLan.setVisible(false);
           jPanelNhieuNgay.setVisible(true);
        }
        
         if(radioMotLan.isSelected())
        {
            jLabelGioKetthuc.setEnabled(false);
            txtGioKetThuc.setEnabled(false);
            cbCachKhoang.setEnabled(false);
            txtKhoang.setEnabled(false);
            txtGioBatDau.setEnabled(false);
            txtGioBatDauMotLanMoiNgay.setEnabled(true);
            jLabel7.setEnabled(true);
            
        }
        
    }
    
    SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
    java.util.Date date = java.util.Calendar.getInstance().getTime();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup3 = new javax.swing.ButtonGroup();
        radioMotNgay = new javax.swing.JRadioButton();
        btnBatDau = new javax.swing.JButton();
        radioNhieuNgay = new javax.swing.JRadioButton();
        jButtonQuayLai = new javax.swing.JButton();
        txtTenJob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelNhieuNgay = new javax.swing.JPanel();
        radioMotLan = new javax.swing.JRadioButton();
        radioCachKhoang = new javax.swing.JRadioButton();
        txtKhoang = new javax.swing.JTextField();
        cbCachKhoang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtGioBatDau = new javax.swing.JTextField();
        jLabelGioKetthuc = new javax.swing.JLabel();
        txtGioKetThuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateNgayBatDauMoiNgay = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtGioBatDauMotLanMoiNgay = new javax.swing.JTextField();
        jDatengayKetThucMoiNgay = new com.toedter.calendar.JDateChooser();
        radioNgayKetThuc = new javax.swing.JRadioButton();
        radioKhongKetThuc = new javax.swing.JRadioButton();
        jPanelMotLan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtGioBatDau1Lan = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        buttonGroup1.add(radioMotNgay);
        radioMotNgay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioMotNgay.setSelected(true);
        radioMotNgay.setText("Một Ngày");
        radioMotNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMotNgayActionPerformed(evt);
            }
        });

        btnBatDau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBatDau.setText("Bắt đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioNhieuNgay);
        radioNhieuNgay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioNhieuNgay.setText("Mỗi ngày");
        radioNhieuNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNhieuNgayActionPerformed(evt);
            }
        });

        jButtonQuayLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonQuayLai.setText("Quay Lại ");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tên (KHÔNG BẮT BUỘC)");

        jPanelNhieuNgay.setBackground(new java.awt.Color(255, 255, 153));

        buttonGroup2.add(radioMotLan);
        radioMotLan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioMotLan.setSelected(true);
        radioMotLan.setText("Một lần");
        radioMotLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMotLanActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioCachKhoang);
        radioCachKhoang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioCachKhoang.setText("Cách khoảng");
        radioCachKhoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCachKhoangActionPerformed(evt);
            }
        });

        cbCachKhoang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbCachKhoang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giờ", "Phút", "Giây" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Giờ bắt đầu");

        jLabelGioKetthuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGioKetthuc.setText("Giờ kết thúc");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ngày bắt đầu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Giờ bắt đầu");

        buttonGroup3.add(radioNgayKetThuc);
        radioNgayKetThuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioNgayKetThuc.setSelected(true);
        radioNgayKetThuc.setText("Ngày Kết Thúc");
        radioNgayKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNgayKetThucActionPerformed(evt);
            }
        });

        buttonGroup3.add(radioKhongKetThuc);
        radioKhongKetThuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radioKhongKetThuc.setText("Không Kết thúc");
        radioKhongKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKhongKetThucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNhieuNgayLayout = new javax.swing.GroupLayout(jPanelNhieuNgay);
        jPanelNhieuNgay.setLayout(jPanelNhieuNgayLayout);
        jPanelNhieuNgayLayout.setHorizontalGroup(
            jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNhieuNgayLayout.createSequentialGroup()
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioMotLan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNhieuNgayLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(txtGioBatDauMotLanMoiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNhieuNgayLayout.createSequentialGroup()
                        .addComponent(txtKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCachKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGioKetthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGioKetThuc)
                            .addComponent(txtGioBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(radioCachKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
            .addGroup(jPanelNhieuNgayLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateNgayBatDauMoiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243)
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioKhongKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jDatengayKetThucMoiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanelNhieuNgayLayout.setVerticalGroup(
            jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNhieuNgayLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCachKhoang)
                    .addComponent(radioMotLan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtGioBatDauMotLanMoiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNhieuNgayLayout.createSequentialGroup()
                        .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCachKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtGioBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGioKetthuc)
                            .addComponent(txtGioKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNgayKetThuc)
                    .addGroup(jPanelNhieuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateNgayBatDauMoiNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDatengayKetThucMoiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(radioKhongKetThuc)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelMotLan.setBackground(new java.awt.Color(204, 255, 204));
        jPanelMotLan.setForeground(new java.awt.Color(255, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ngày bắt đầu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Giờ bắt đầu");

        javax.swing.GroupLayout jPanelMotLanLayout = new javax.swing.GroupLayout(jPanelMotLan);
        jPanelMotLan.setLayout(jPanelMotLanLayout);
        jPanelMotLanLayout.setHorizontalGroup(
            jPanelMotLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotLanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(txtGioBatDau1Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanelMotLanLayout.setVerticalGroup(
            jPanelMotLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotLanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMotLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMotLanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGioBatDau1Lan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(btnBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(radioMotNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(radioNhieuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtTenJob, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNhieuNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMotLan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenJob, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMotNgay)
                    .addComponent(radioNhieuNgay))
                .addGap(48, 48, 48)
                .addComponent(jPanelMotLan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanelNhieuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
       
        
        //txtGioKetThuc.getText()
        String ngayBatDau=null,gioBatDau1Lan=null,gioKetThuc=null,gioBatDau=null,NgayBatDauMoiNgay=null,ngayKetThucMoiNgay=null,GioBatDauMotLanMoiNgay=null;
        
        if(radioMotNgay.isSelected())
        {
            ngayBatDau = ft.format(jDateNgayBatDau.getDate());

            ngayBatDau = ngayBatDau.replaceAll("-", "");
            System.out.println("" + ngayBatDau);


            gioBatDau1Lan = txtGioBatDau1Lan.getText();
            gioBatDau1Lan = gioBatDau1Lan.replaceAll(":", "");
        }
        else
        {
            gioKetThuc = txtGioKetThuc.getText();
            gioKetThuc = gioKetThuc.replaceAll(":", ""); 

            gioBatDau = txtGioBatDau.getText();
            gioBatDau = gioBatDau.replaceAll(":", "");


            NgayBatDauMoiNgay = ft.format(jDateNgayBatDauMoiNgay.getDate());

            NgayBatDauMoiNgay = NgayBatDauMoiNgay.replaceAll("-", "");


            ngayKetThucMoiNgay = ft.format(jDatengayKetThucMoiNgay.getDate());

            ngayKetThucMoiNgay = ngayKetThucMoiNgay.replaceAll("-", "");        




            GioBatDauMotLanMoiNgay = txtGioBatDauMotLanMoiNgay.getText();
            GioBatDauMotLanMoiNgay = GioBatDauMotLanMoiNgay.replaceAll(":", "");
        }
        
        
        
        
        
        String tenJob = txtTenJob.getText() + java.time.LocalDateTime.now().toString();
        
        
        
                
        
        if (radioMotNgay.isSelected()) { // 1 ngay
            
            // chia ra 1 ngày 1 lần, cách khoảng
           
            
            try {
            // TODO add your handling code here:
                String sql = "EXEC BACK_UP_NGAY '" + tenJob + "','" + ngayBatDau + "','" + gioBatDau1Lan + "';";
                Connection con = DataBaseHelper.getConnection();
                PreparedStatement smt = con.prepareStatement(sql);
                boolean kt = smt.execute();
                if(!kt)  JOptionPane.showMessageDialog(this, "BackUP auto thành công : " + txtTenJob.getText());
                
            } 
            catch (SQLException ex) 
            {
            Logger.getLogger(BACKUPAUTO.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        else 
            
        { // moi ngay cách khoảng  (chưa làm mỗi ngày 1 lần + 1 ngày cách khoảng)
            
            
            int loai = 4; // daily
            int gio_phut_giay;
            if (cbCachKhoang.getSelectedItem().toString().equals("Giờ")) 
            {
                gio_phut_giay = 8;
                
            } else if (cbCachKhoang.getSelectedItem().toString().equals("Phút")) {
                
                gio_phut_giay = 4;
                
            } else 
            {
                
                gio_phut_giay = 2;
            }
           
               // String sql = "EXEC BACK_UP_NGAY_CACH KHOANG_THOI_GIAN '100', " + loai + ", " + gio_phut_giay + "," + txtKhoang.getText() +", '" + txtNgayBatDau.getText() + "','" + txtGioBatDau.getText() + "','" + txtGioKetThuc.getText() + "';";
                      String sqlMotLanMoiNgay = "EXEC BACK_UP_MOT_LAN_MOI_NGAY '" + tenJob + "', " + loai + "," + NgayBatDauMoiNgay + "," + GioBatDauMotLanMoiNgay ;
                      
                      String sqlMotLanMoiNgaykT = "EXEC BACK_UP_MOT_LAN_MOI_NGAY_KT '" + tenJob + "', " + loai + "," + NgayBatDauMoiNgay + "," + ngayKetThucMoiNgay + "," + GioBatDauMotLanMoiNgay ;        
                      String sqlNhieuLanTrongNgay = "EXEC BACK_UP_NGAY_CACH_KHOANG_THOI_GIAN '" + tenJob + "', " + loai + "," + gio_phut_giay + "," + txtKhoang.getText() + ",'" + NgayBatDauMoiNgay + "','" + gioBatDau + "','" + gioKetThuc + "';";
                      String sqlNhieuLanTrongNgayKt = "BACK_UP_NGAY_CACH_KHOANG_THOI_GIAN_CO_KET_THUC '" + tenJob + "', " + loai + "," + gio_phut_giay + "," + txtKhoang.getText() + ",'" + NgayBatDauMoiNgay + "','" + ngayKetThucMoiNgay + "','" + gioBatDau + "','" + gioKetThuc + "';";
                      
                    try {
                    Connection con = DataBaseHelper.getConnection();
                    String sql =null;
                    if(radioMotLan.isSelected())
                        if(radioNgayKetThuc.isSelected())
                            sql = sqlMotLanMoiNgaykT;
                        else
                            sql = sqlMotLanMoiNgay;
                    else
                        if(radioNgayKetThuc.isSelected())
                            sql = sqlNhieuLanTrongNgay;
                        else
                            sql = sqlNhieuLanTrongNgayKt;
                    
                           
                    PreparedStatement smt = con.prepareStatement(sql);
                    boolean kt = smt.execute();
                    if(!kt)  JOptionPane.showMessageDialog(this, "BackUP auto thành công : " + txtTenJob.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(BACKUPAUTO.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
        
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void radioMotLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMotLanActionPerformed
        // TODO add your handling code here:
        if(radioMotLan.isSelected())
        {
            jLabelGioKetthuc.setEnabled(false);
            txtGioKetThuc.setEnabled(false);
            cbCachKhoang.setEnabled(false);
            txtKhoang.setEnabled(false);
            txtGioBatDau.setEnabled(false);
            txtGioBatDauMotLanMoiNgay.setEnabled(true);
            jLabel7.setEnabled(true);
            
        }
      
       
    }//GEN-LAST:event_radioMotLanActionPerformed

    private void radioCachKhoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCachKhoangActionPerformed
        // TODO add your handling code here:
        
        if(radioCachKhoang.isSelected())
        {
            jLabelGioKetthuc.setEnabled(true);
            txtGioKetThuc.setEnabled(true);
            cbCachKhoang.setEnabled(true);
            txtKhoang.setEnabled(true);
            txtGioBatDau.setEnabled(true);
            txtGioBatDauMotLanMoiNgay.setEnabled(false);
            jLabel7.setEnabled(false);
            
        }

    }//GEN-LAST:event_radioCachKhoangActionPerformed

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        // TODO add your handling code here:
    
            this.setVisible(false);
            new FormBackUp().setVisible(true);;
        
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    private void radioMotNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMotNgayActionPerformed
        // TODO add your handling code here:
        if(radioMotNgay.isSelected())
        {
            jPanelMotLan.setVisible(true);
            jPanelNhieuNgay.setVisible(false);
        }
            
        else
        {
           jPanelMotLan.setVisible(false);
           jPanelNhieuNgay.setVisible(true);
        }
    }//GEN-LAST:event_radioMotNgayActionPerformed

    private void radioNhieuNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNhieuNgayActionPerformed
        // TODO add your handling code here:
        if(radioMotNgay.isSelected())
        {
            jPanelMotLan.setVisible(true);
            jPanelNhieuNgay.setVisible(false);
        }
            
        else
        {
           jPanelMotLan.setVisible(false);
           jPanelNhieuNgay.setVisible(true);
        }
    }//GEN-LAST:event_radioNhieuNgayActionPerformed

    private void radioNgayKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNgayKetThucActionPerformed
        // TODO add your handling code here:
        if(radioNgayKetThuc.isSelected())
            jDatengayKetThucMoiNgay.setEnabled(true);
        else
            jDatengayKetThucMoiNgay.setEnabled(false);
    }//GEN-LAST:event_radioNgayKetThucActionPerformed

    private void radioKhongKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKhongKetThucActionPerformed
        // TODO add your handling code here:
        if(radioNgayKetThuc.isSelected())
            jDatengayKetThucMoiNgay.setEnabled(true);
        else
            jDatengayKetThucMoiNgay.setEnabled(false);
    }//GEN-LAST:event_radioKhongKetThucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BACKUPAUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BACKUPAUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BACKUPAUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BACKUPAUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BACKUPAUTO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbCachKhoang;
    private javax.swing.JButton jButtonQuayLai;
    private com.toedter.calendar.JDateChooser jDateNgayBatDau;
    private com.toedter.calendar.JDateChooser jDateNgayBatDauMoiNgay;
    private com.toedter.calendar.JDateChooser jDatengayKetThucMoiNgay;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelGioKetthuc;
    private javax.swing.JPanel jPanelMotLan;
    private javax.swing.JPanel jPanelNhieuNgay;
    private javax.swing.JRadioButton radioCachKhoang;
    private javax.swing.JRadioButton radioKhongKetThuc;
    private javax.swing.JRadioButton radioMotLan;
    private javax.swing.JRadioButton radioMotNgay;
    private javax.swing.JRadioButton radioNgayKetThuc;
    private javax.swing.JRadioButton radioNhieuNgay;
    private javax.swing.JTextField txtGioBatDau;
    private javax.swing.JTextField txtGioBatDau1Lan;
    private javax.swing.JTextField txtGioBatDauMotLanMoiNgay;
    private javax.swing.JTextField txtGioKetThuc;
    private javax.swing.JTextField txtKhoang;
    private javax.swing.JTextField txtTenJob;
    // End of variables declaration//GEN-END:variables
}
