/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BACKUP_RESTORE;

import design.DataBaseHelper;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ADMIN
 */
public class Restore extends javax.swing.JFrame {

    /**
     * Creates new form Restore
     */
    public Restore() {
        initComponents();
       txtRestoreFull.setEnabled(false);
        bnbRestore.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        bnbRestore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bnbFileFull = new javax.swing.JButton();
        txtRestoreFull = new javax.swing.JTextField();
        jButtonQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bnbRestore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bnbRestore.setText("Restore");
        bnbRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbRestoreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("File Restore Full:");

        bnbFileFull.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bnbFileFull.setText("Chọn File");
        bnbFileFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbFileFullActionPerformed(evt);
            }
        });

        jButtonQuayLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonQuayLai.setText("Quay Lại ");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRestoreFull, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(bnbFileFull, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(bnbRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRestoreFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnbFileFull))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonQuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnbRestore, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnbRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbRestoreActionPerformed
        // TODO add your handling code here:
       
        String sql="USE [master];" +
                " IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'qldiem') " +
                " CREATE DATABASE [qldiem]" +
                "ALTER DATABASE [qldiem] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;" +
                "RESTORE DATABASE [qldiem] FROM  DISK = N'" + txtRestoreFull.getText() +"' WITH REPLACE;" +
                "ALTER DATABASE [qldiem] SET MULTI_USER";
        
        try {
            Connection con = DataBaseHelper.getConnection();
            PreparedStatement smt = con.prepareStatement(sql);
            
            boolean  kt = smt.execute();
            
            if(!kt)  JOptionPane.showMessageDialog(this, "Restore thành công!!!");
            
           //labeltc.setVisible(true);
        } catch (Exception e) {
             e.printStackTrace();
        }
    }//GEN-LAST:event_bnbRestoreActionPerformed

    private void bnbFileFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbFileFullActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        choose.setCurrentDirectory(new File("C:\\backup"));
        FileNameExtensionFilter ff = new FileNameExtensionFilter("File", "bak");
        choose.setFileFilter(ff);
        int x = choose.showDialog(this, "Chọn File");
        if(x == JFileChooser.APPROVE_OPTION)
        {
            String f =  choose.getSelectedFile().getAbsolutePath();
            txtRestoreFull.setText(f);
        }
        if(txtRestoreFull.getText().equals(""))
        bnbRestore.setEnabled(false);
        else
        bnbRestore.setEnabled(true);
    }//GEN-LAST:event_bnbFileFullActionPerformed

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        // TODO add your handling code here:
        int click = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn quay lại.");
        if (click == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new FormBackUp().setVisible(true);;
        }
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnbFileFull;
    private javax.swing.JButton bnbRestore;
    private javax.swing.JButton jButtonQuayLai;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRestoreFull;
    // End of variables declaration//GEN-END:variables
}
