/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.main;

import doan.DataBaseHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danh
 */
public class KeHoach extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    String maCnKh = null;
    public KeHoach(String maCn) {
        initComponents();
        maCnKh = maCn;
        listMh.setMultipleMode(true);
        listMhChon.setMultipleMode(true);
        //vohieuButtonKhiChuaChon();
        loadDsMh();
        initDataMhCn();
        
    }
    DefaultTableModel model = new DefaultTableModel();

    private KeHoach() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void initDataMhCn()
    {
        model = (DefaultTableModel) jTableDSmhcn.getModel();
        String sql = "select tenmh,hesoth,hesock from kehoach,monhoc where kehoach.mamh=monhoc.mamh and kehoach.macn='"+ maCnKh +"'";
        model.setRowCount(0);
        try (Connection con = DataBaseHelper.getConnection();
                Statement smt = con.createStatement();) {
            Vector vt;
            ResultSet rs = smt.executeQuery(sql);
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                model.addRow(vt);
            }
            jTableDSmhcn.setModel(model);

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public String searchMaMonHoc(String tenMonHoc) {
        String sql = " SELECT mamh FROM monhoc WHERE tenmh=N'" + tenMonHoc + "'";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                return rs.getString(1);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
    
    public void loadDsMh()
    {   
        listMh.removeAll();
        try(Connection con = DataBaseHelper.getConnection();
                PreparedStatement smt = con.prepareStatement("{call DS_MH_CHUACHON(?)}");)
        {   
            
            smt.setString(1,maCnKh);
            ResultSet rs = smt.executeQuery();
            
            while(rs.next())
            {
                listMh.add(rs.getString(1));
            }
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void lamMoiMhcn() {
        jTextHsTh.setText("");
        jTextHsck.setText("");
        jLabelTenMhcn.setText("");
    }
    
    public boolean checkMhChon(String tenMh)
    {   

        try(Connection con = DataBaseHelper.getConnection();
                PreparedStatement smt = con.prepareStatement("{call DS_MHCHON(?)}");)
        {   
            
            smt.setString(1,maCnKh);
            ResultSet rs = smt.executeQuery();
            
            while(rs.next())
            {
                if(rs.getString(1).equals(tenMh)) return true;
            }
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKeHoach = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDSmhcn = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextHsTh = new javax.swing.JTextField();
        jTextHsck = new javax.swing.JTextField();
        jButtonsuamhcn = new javax.swing.JButton();
        jButtonxoamhcn = new javax.swing.JButton();
        jLabelTenMhcn = new javax.swing.JLabel();
        jButtonaddMhcn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonGo = new javax.swing.JButton();
        listMh = new java.awt.List();
        listMhChon = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelKeHoach.setBorder(javax.swing.BorderFactory.createTitledBorder("Kế Hoach"));
        jPanelKeHoach.setToolTipText("zvds");
        jPanelKeHoach.setName("Kế Hoạch"); // NOI18N
        jPanelKeHoach.setOpaque(false);

        jTableDSmhcn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Môn Học", "Hệ số thực hành", "Hệ số cuối kỳ"
            }
        ));
        jTableDSmhcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSmhcnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDSmhcn);

        jLabel7.setText("Hệ số thực hành:");

        jLabel8.setText("Hệ số cuối kỳ:");

        jLabel9.setText("Môn Học:");

        jButtonsuamhcn.setText("Sửa");
        jButtonsuamhcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuamhcnActionPerformed(evt);
            }
        });

        jButtonxoamhcn.setText("xóa");
        jButtonxoamhcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoamhcnActionPerformed(evt);
            }
        });

        jButtonaddMhcn.setText("add");
        jButtonaddMhcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddMhcnActionPerformed(evt);
            }
        });

        jLabel10.setText("DS_MonChuaChon");

        jLabel11.setText("DS_MonHocChon");

        jButtonBack.setText("<");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonGo.setText(">");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        listMh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKeHoachLayout = new javax.swing.GroupLayout(jPanelKeHoach);
        jPanelKeHoach.setLayout(jPanelKeHoachLayout);
        jPanelKeHoachLayout.setHorizontalGroup(
            jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                        .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                                        .addComponent(listMh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonGo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(listMhChon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel11)))
                                .addGap(39, 39, 39)
                                .addComponent(jButtonaddMhcn))
                            .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTenMhcn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextHsTh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextHsck, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonxoamhcn)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsuamhcn)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelKeHoachLayout.setVerticalGroup(
            jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonGo)
                                    .addComponent(jButtonBack)))
                            .addComponent(listMhChon, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(listMh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelKeHoachLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButtonaddMhcn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKeHoachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jTextHsTh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextHsck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonsuamhcn)
                        .addComponent(jButtonxoamhcn))
                    .addComponent(jLabelTenMhcn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelKeHoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelKeHoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDSmhcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSmhcnMouseClicked
        // TODO add your handling code here:
        int row = jTableDSmhcn.getSelectedRow();
        if(row>=0)
        {
            jLabelTenMhcn.setText(jTableDSmhcn.getValueAt(row, 0).toString().toUpperCase());
            jTextHsTh.setText(jTableDSmhcn.getValueAt(row, 1).toString());
            jTextHsck.setText(jTableDSmhcn.getValueAt(row, 2).toString());
            jButtonsuamhcn.setEnabled(true);
            jButtonxoamhcn.setEnabled(true);
        }
    }//GEN-LAST:event_jTableDSmhcnMouseClicked

    private void jButtonsuamhcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuamhcnActionPerformed
        // TODO add your handling code here:
        int kt = JOptionPane.showConfirmDialog(this, "ban chan chan muon sua khong");
        if (kt == JOptionPane.CANCEL_OPTION) {
            return;
        } else if (kt == JOptionPane.OK_OPTION) {
            String sql = "update kehoach set hesoth=?,hesock=? where macn = ? and mamh=?";
            try (Connection con = DataBaseHelper.getConnection();
                PreparedStatement smt = con.prepareStatement(sql);) {

                smt.setString(3, maCnKh);
                smt.setString(4, searchMaMonHoc(jLabelTenMhcn.getText()));

                smt.setFloat(1,  Float.valueOf(jTextHsTh.getText()) );
                smt.setFloat(2, Float.valueOf(jTextHsck.getText()) );
                int kt2 = smt.executeUpdate();
                if (kt2 > 0) {
                    JOptionPane.showMessageDialog(this, "update thanh cong");
                }
                initDataMhCn();
                lamMoiMhcn();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
        }
    }//GEN-LAST:event_jButtonsuamhcnActionPerformed

    private void jButtonxoamhcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoamhcnActionPerformed
        // TODO add your handling code here:
        int kt = JOptionPane.showConfirmDialog(this, "ban co muon xoa khong");
        if (kt == JOptionPane.CANCEL_OPTION) {
            return;
        } else if (kt == JOptionPane.OK_OPTION) {
            String sql = "delete from kehoach where macn=? and mamh=?";
            try (Connection con = DataBaseHelper.getConnection();
                PreparedStatement smt = con.prepareStatement(sql);) {
                smt.setString(1, maCnKh);
                smt.setString(2,searchMaMonHoc(jLabelTenMhcn.getText()));
                int kt2 = smt.executeUpdate();
                if (kt2 > 0) {
                    JOptionPane.showMessageDialog(this, "xoa thanh cong");
                }
                initDataMhCn();
                lamMoiMhcn();
                loadDsMh();
                //  loadDsMhChon();
                listMhChon.removeAll();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonxoamhcnActionPerformed

    private void jButtonaddMhcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddMhcnActionPerformed
        // TODO add your handling code here:
        
        String sql2 = "insert into kehoach values(?,?,0,0)";
        try (Connection con = DataBaseHelper.getConnection();
            PreparedStatement smt = con.prepareStatement(sql2)) {
            int kt=0;
            for(String mh: listMhChon.getItems())
            {

                if(checkMhChon(mh)==false)
                {
                    smt.setString(1, maCnKh);
                    smt.setString(2, searchMaMonHoc(mh));
                    kt = smt.executeUpdate();
                }

            }

            if (kt > 0) {
                JOptionPane.showMessageDialog(this, "insert thanh cong");
            }
            initDataMhCn();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        listMhChon.removeAll();

    }//GEN-LAST:event_jButtonaddMhcnActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        if(listMhChon.getSelectedIndexes()!=null)
        for (String a : listMhChon.getSelectedItems()) {
            listMh.add(a);
            listMhChon.remove(a);
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        // TODO add your handling code here:

        if(listMh.getSelectedIndexes()!=null)
        for (String a : listMh.getSelectedItems()) {
            listMhChon.add(a);
            listMh.remove(a);
        }

    }//GEN-LAST:event_jButtonGoActionPerformed

    private void listMhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listMhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeHoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeHoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonaddMhcn;
    private javax.swing.JButton jButtonsuamhcn;
    private javax.swing.JButton jButtonxoamhcn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTenMhcn;
    private javax.swing.JPanel jPanelKeHoach;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDSmhcn;
    private javax.swing.JTextField jTextHsTh;
    private javax.swing.JTextField jTextHsck;
    private java.awt.List listMh;
    private java.awt.List listMhChon;
    // End of variables declaration//GEN-END:variables
}
