/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author danh
 */
public class JPanelTrigger extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTrigger
     */
    public JPanelTrigger() {
        initComponents();
        txtThongBao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxNgayLTC = new javax.swing.JCheckBox();
        jCheckBoxSLLTC = new javax.swing.JCheckBox();
        jCheckBoxslsinhvienlop = new javax.swing.JCheckBox();
        jCheckBoxsldangltc = new javax.swing.JCheckBox();
        jCheckBoxdiemSV = new javax.swing.JCheckBox();
        jButtonLuu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtThongBao = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jCheckBoxNgayLTC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxNgayLTC.setText("Ngày Lớp Tín Chỉ");

        jCheckBoxSLLTC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxSLLTC.setText("Số lượng tối thiểu tối đa lớp tín chỉ");

        jCheckBoxslsinhvienlop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxslsinhvienlop.setText("Số lượng sinh viên của một lớp");

        jCheckBoxsldangltc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxsldangltc.setText("Số lượng đăng kí lớp tín chỉ");

        jCheckBoxdiemSV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxdiemSV.setText("điểm sinh viên");

        jButtonLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLuu.setText("Lưu");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRIGGER");

        txtThongBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(255, 51, 51));
        txtThongBao.setText("Thông báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxNgayLTC)
                            .addComponent(jCheckBoxdiemSV))
                        .addGap(359, 359, 359)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxslsinhvienlop)
                            .addComponent(jCheckBoxsldangltc)
                            .addComponent(jCheckBoxSLLTC)
                            .addComponent(jButtonLuu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNgayLTC)
                    .addComponent(jCheckBoxslsinhvienlop))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jCheckBoxdiemSV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBoxsldangltc)
                        .addGap(34, 34, 34)
                        .addComponent(jCheckBoxSLLTC)))
                .addGap(42, 42, 42)
                .addComponent(txtThongBao)
                .addGap(10, 10, 10)
                .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        // TODO add your handling code here:
        ArrayList<String> querys = new ArrayList<String>(); 
        if(jCheckBoxNgayLTC.isSelected())
            querys.add("ALTER TABLE LopTinChi ENABLE TRIGGER trg_NgayLoptinChi");
        else
            querys.add("ALTER TABLE LopTinChi DISABLE TRIGGER trg_NgayLoptinChi");

        if(jCheckBoxdiemSV.isSelected())
            querys.add("ALTER TABLE DANGKI ENABLE TRIGGER trg_diemSinhVien");
        else
            querys.add("ALTER TABLE DANGKI DISABLE TRIGGER trg_diemSinhVien");
        
        if(jCheckBoxslsinhvienlop.isSelected())
            querys.add("ALTER TABLE SINHVIEN ENABLE TRIGGER trg_SoLuongSinhVienLop");
        else
            querys.add("ALTER TABLE SINHVIEN DISABLE TRIGGER trg_SoLuongSinhVienLop");
        
        
        
        if(jCheckBoxsldangltc.isSelected())
            querys.add("ALTER TABLE DANGKI ENABLE TRIGGER trg_SoLuongDangKyLTC");
        else
            querys.add("ALTER TABLE DANGKI DISABLE TRIGGER trg_SoLuongDangKyLTC");
        
        if(jCheckBoxSLLTC.isSelected())
            querys.add("ALTER TABLE LopTinChi ENABLE TRIGGER trg_SoluongLopTinChi");
        else
            querys.add("ALTER TABLE LopTinChi DISABLE TRIGGER trg_SoluongLopTinChi");
        

        try (Connection con = DataBaseHelper.getConnection();) 
        {
            
            for(String sql : querys)
            {
               PreparedStatement smt = con.prepareStatement(sql);
               smt.executeUpdate();
            }
            
            txtThongBao.setVisible(true);
            txtThongBao.setForeground(Color.BLUE);
            txtThongBao.setText("Thành công");

        } catch (SQLException ex) {
            txtThongBao.setVisible(true);
            txtThongBao.setText("Thất bại");
            txtThongBao.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JCheckBox jCheckBoxNgayLTC;
    private javax.swing.JCheckBox jCheckBoxSLLTC;
    private javax.swing.JCheckBox jCheckBoxdiemSV;
    private javax.swing.JCheckBox jCheckBoxsldangltc;
    private javax.swing.JCheckBox jCheckBoxslsinhvienlop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtThongBao;
    // End of variables declaration//GEN-END:variables
}
