/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author danh
 */
public class JPanelXoaLoginUser extends javax.swing.JPanel {

    /**
     * Creates new form JPanelXoaLoginUser
     */
    public JPanelXoaLoginUser() {
        initComponents();
        lbThongBaoKhongTonTai.setVisible(false);
        txtThongBao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtLoginname = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lbThongBaoKhongTonTai = new javax.swing.JLabel();
        txtThongBao = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập: ");

        txtLoginname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtLoginname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginnameKeyPressed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTim.setText("Xóa");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        lbThongBaoKhongTonTai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbThongBaoKhongTonTai.setForeground(new java.awt.Color(255, 0, 0));
        lbThongBaoKhongTonTai.setText("Tên đăng nhập không tồn tại!");

        txtThongBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(255, 51, 51));
        txtThongBao.setText("Thông báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongBaoKhongTonTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginname, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoginname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbThongBaoKhongTonTai)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThongBao)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        // kiểm tra xem có tồn tại tài khoản
        String sql = "SELECT name FROM master.sys.sql_logins WHERE name <> 'sa';";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            boolean tonTaiTK = false;
            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase(txtLoginname.getText())) {
                    tonTaiTK = true;
                    break;
                }
            }
            if (!tonTaiTK) {
                lbThongBaoKhongTonTai.setVisible(true);
                return;
            }
            lbThongBaoKhongTonTai.setVisible(false);
          
            // lấy role của tài khoản để set vào label tên role hiện tại
            sql = "EXEC Xoa_Login '" + txtLoginname.getText()+ "'";
            PreparedStatement ps = con.prepareStatement(sql);
            boolean kt = ps.execute();
            if(!kt)
            {
                txtThongBao.setText("Xóa thành công !");
                txtThongBao.setForeground(Color.BLUE);
                txtThongBao.setVisible(true);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        lbThongBaoKhongTonTai.setVisible(false);
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void txtLoginnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginnameKeyPressed
        // TODO add your handling code here:
        lbThongBaoKhongTonTai.setVisible(false);
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_txtLoginnameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbThongBaoKhongTonTai;
    private javax.swing.JTextField txtLoginname;
    private javax.swing.JLabel txtThongBao;
    // End of variables declaration//GEN-END:variables
}
