/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author danh
 */
public class JPanelRole extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTaoRole
     */
    public JPanelRole() {
        initComponents();
        txttb.setVisible(false);
        txtThanhCong.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRoleName = new javax.swing.JTextField();
        btnTaoRole = new javax.swing.JButton();
        txttb = new javax.swing.JLabel();
        txtThanhCong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXoaRole = new javax.swing.JButton();

        txtRoleName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        btnTaoRole.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTaoRole.setText("Tạo");
        btnTaoRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoRoleActionPerformed(evt);
            }
        });

        txttb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttb.setForeground(new java.awt.Color(255, 0, 0));
        txttb.setText("Tên Role đã có trong cơ sở dữ liệu");

        txtThanhCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThanhCong.setForeground(new java.awt.Color(0, 102, 255));
        txtThanhCong.setText("Tạo Role Thành Công!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO XÓA ROLE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên Role:");

        btnXoaRole.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaRole.setText("Xóa");
        btnXoaRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThanhCong, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttb, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnXoaRole, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(btnTaoRole, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThanhCong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaRole, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoRole, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoRoleActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT name FROM sys.database_principals WHERE type_desc = 'DATABASE_ROLE' AND principal_id < 16000 and name <> 'public'";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            boolean trungTen = false;
            while (rs.next()) {
                System.out.println(rs.getString(1));
                if (rs.getString(1).equalsIgnoreCase(txtRoleName.getText())) {
                    trungTen = true;
                    break;
                }
            }
            if (trungTen) {
                System.out.println("Trung ten");
                txttb.setVisible(true);
                txtThanhCong.setVisible(false);
            } else {
                sql = "CREATE ROLE " + txtRoleName.getText();
                try {
                    con = DataBaseHelper.getConnection();
                    st = con.createStatement();
                    st.execute(sql);
                    txttb.setVisible(false);
                    txtThanhCong.setVisible(true);
                } catch (Exception e) {
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTaoRoleActionPerformed

    private void btnXoaRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaRoleActionPerformed
        // TODO add your handling code here:
         String sql = "SELECT name FROM sys.database_principals WHERE type_desc = 'DATABASE_ROLE' AND principal_id < 16000 and name <> 'public'";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            boolean trungTen = false;
            while (rs.next()) {
                System.out.println(rs.getString(1));
                if (rs.getString(1).equalsIgnoreCase(txtRoleName.getText())) {
                    trungTen = true;
                    break;
                }
            }
            if (!trungTen) {
                System.out.println("Trung ten");
                txttb.setText("Role không tồn tại ");
                txttb.setVisible(true);
                txtThanhCong.setVisible(false);
            } else {
                sql = "DROP ROLE " + txtRoleName.getText().toUpperCase();
                try {
                    con = DataBaseHelper.getConnection();
                    st = con.createStatement();
                    boolean kt = st.execute(sql);
                   if(!kt)
                   {
                        txtThanhCong.setText("Xóa role thành công ");
                        txttb.setVisible(false);
                        txtThanhCong.setVisible(true);
                   }
                  
                } catch (Exception e) {
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnXoaRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoRole;
    private javax.swing.JButton btnXoaRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRoleName;
    private javax.swing.JLabel txtThanhCong;
    private javax.swing.JLabel txttb;
    // End of variables declaration//GEN-END:variables
}
