/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author danh
 */
public class JPanelCapQuyenChoRole extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCapQuyenChoRole
     */
    public JPanelCapQuyenChoRole() {
        initComponents();
        txtThongBao.setVisible(false);
        
         String sql = "SELECT name FROM sys.database_principals WHERE type_desc = 'DATABASE_ROLE' AND principal_id < 16000 and name <> 'public'";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
        
            while (rs.next()) {
                comboBoxTenRole.addItem(rs.getString(1));
            }
         
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxTenRole = new javax.swing.JComboBox<>();
        cbToanBoQuyen = new javax.swing.JCheckBox();
        cbxem = new javax.swing.JCheckBox();
        cbghi = new javax.swing.JCheckBox();
        cbTaoTaiKhoan = new javax.swing.JCheckBox();
        btnCap = new javax.swing.JButton();
        txtThongBao = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cấp quyền cho Role");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên Role:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Quyền:");

        comboBoxTenRole.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboBoxTenRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTenRoleActionPerformed(evt);
            }
        });

        cbToanBoQuyen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbToanBoQuyen.setText("Toàn bộ quyền trên database");
        cbToanBoQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToanBoQuyenActionPerformed(evt);
            }
        });

        cbxem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbxem.setText("Chỉ được xem");

        cbghi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbghi.setText("Được xem và ghi");

        cbTaoTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbTaoTaiKhoan.setText("Được tạo tài khoản login");
        cbTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTaoTaiKhoanActionPerformed(evt);
            }
        });

        btnCap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCap.setText("Xác nhận");
        btnCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapActionPerformed(evt);
            }
        });

        txtThongBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(255, 51, 51));
        txtThongBao.setText("Thông báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbToanBoQuyen)
                            .addComponent(cbxem)
                            .addComponent(cbghi)
                            .addComponent(cbTaoTaiKhoan)
                            .addComponent(comboBoxTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnCap, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxTenRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbToanBoQuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbghi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTaoTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThongBao)
                    .addComponent(btnCap, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbToanBoQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToanBoQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbToanBoQuyenActionPerformed

    private void cbTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTaoTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTaoTaiKhoanActionPerformed

    private void btnCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapActionPerformed
        // TODO add your handling code here:
        String sql;
        try {
            Connection con = DataBaseHelper.getConnection();
            PreparedStatement ps;
            if (cbToanBoQuyen.isSelected()) {
                sql = "EXEC sp_addrolemember 'db_owner', '" + comboBoxTenRole.getSelectedItem().toString() + "'";
                ps = con.prepareStatement(sql);
                ps.execute();
            }
            if (cbxem.isSelected()) {
                if (!cbToanBoQuyen.isSelected()) {
                    sql = "EXEC sp_addrolemember 'db_datareader', '" + comboBoxTenRole.getSelectedItem().toString() + "'";
                    ps = con.prepareStatement(sql);
                    ps.execute();
                }

            }
            if (cbghi.isSelected()) {
                if (!cbToanBoQuyen.isSelected()) {
                    sql = "EXEC sp_addrolemember 'db_datawriter', '" + comboBoxTenRole.getSelectedItem().toString() + "'";
                    ps = con.prepareStatement(sql);
                    ps.execute();
                }

            }
            if (cbTaoTaiKhoan.isSelected()) {
                if (!cbToanBoQuyen.isSelected()) {
                    sql = "EXEC sp_addrolemember 'db_securityadmin', '" + comboBoxTenRole.getSelectedItem().toString() + "'";
                    ps = con.prepareStatement(sql);
                    ps.execute();
                    sql = "EXEC sp_addrolemember 'db_accessadmin', '" + comboBoxTenRole.getSelectedItem().toString() + "'";
                    ps = con.prepareStatement(sql);
                    ps.execute();
                }

            }
            txtThongBao.setVisible(true);
            txtThongBao.setForeground(Color.BLUE);
            txtThongBao.setText("Cấp quyền thành công");
        } catch (Exception ex) {
            txtThongBao.setVisible(true);
            txtThongBao.setText("Cấp quyền thất bại");
            txtThongBao.setForeground(Color.RED);
        }

    }//GEN-LAST:event_btnCapActionPerformed

    private void comboBoxTenRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTenRoleActionPerformed
        // TODO add your handling code here:
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_comboBoxTenRoleActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCap;
    private javax.swing.JCheckBox cbTaoTaiKhoan;
    private javax.swing.JCheckBox cbToanBoQuyen;
    private javax.swing.JCheckBox cbghi;
    private javax.swing.JCheckBox cbxem;
    private javax.swing.JComboBox<String> comboBoxTenRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtThongBao;
    // End of variables declaration//GEN-END:variables
}
