/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 *
 * @author danh
 */
public class JPanelThemLoginVaoRole extends javax.swing.JPanel {

    /**
     * Creates new form JPanelThemLoginVaoRole
     */
    public JPanelThemLoginVaoRole() {
        initComponents();
        
        txtThongBao.setVisible(false);
        
        // lấy tất cả các role trừ role hệ thống truyền lên
                String sql = "SELECT name FROM sys.database_principals WHERE type = 'R' and principal_id < 16384 and name <> 'public'";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                comboboxRole.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        txtThongBao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        comboboxRole = new javax.swing.JComboBox<>();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtThongBao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtThongBao.setForeground(new java.awt.Color(255, 51, 51));
        txtThongBao.setText("Tên đăng nhập không tồn tại!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM LOGIN VÀO ROLE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Role:");

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(comboboxRole, 0, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(txtThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtThongBao)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // chạy qua tất cả các role để loại bỏ
        // kiểm tra xem tên đăng nhập có tồn tại
        String sql = "SELECT name FROM master.sys.sql_logins;";
        Connection con=null;
        Statement st;
        PreparedStatement ps;
        ResultSet rs;
        try {
            con = DataBaseHelper.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            boolean tonTaiTK = false;
            while (rs.next()) {
                if (rs.getString(1).equals(txtUsername.getText())) {
                    tonTaiTK = true;
                    break;
                }
            }
            if (!tonTaiTK) {
                txtThongBao.setText("Tài khoản không tồn tại");
                txtThongBao.setVisible(true);
                return;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        txtThongBao.setVisible(false);

        // lặp qua tất cả  role hệ thống
        sql = "SELECT name FROM sys.database_principals WHERE type = 'R' and principal_id > 16000";
        String temp = "USE qldiem;";
        try {
            con = DataBaseHelper.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                temp += "EXEC sp_droprolemember '"+ rs.getString(1) +"', '" + txtUsername.getText() + "';";
            }
            System.out.println(temp);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
        // lặp qua tất cả role ko phải hệ thống
        sql = "SELECT name FROM sys.database_principals WHERE type = 'R' and principal_id < 16384 and name <> 'public'";
        try {
            con = DataBaseHelper.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                temp +=" EXEC sp_droprolemember '"+ rs.getString(1) +"', '" + txtUsername.getText() + "';";
            }
            System.out.println(temp);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
        // xóa role
        try {
            con = DataBaseHelper.getConnection();
            ps = con.prepareStatement(temp);
            ps.execute();
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        // add tài khoản vào role đã chọn

        sql = "EXEC sp_addrolemember '" + comboboxRole.getSelectedItem().toString() +"', '" + txtUsername.getText() + "';";

        try {
            con = DataBaseHelper.getConnection();
            ps = con.prepareStatement(sql);
            ps.execute();
            txtThongBao.setText("Thêm thành công !");
            txtThongBao.setForeground(Color.BLUE);
            txtThongBao.setVisible(true);
        }catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        txtThongBao.setVisible(false);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> comboboxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtThongBao;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
