/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTCS;

import design.DataBaseHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author danh
 */
public class JPanelXoaLoginKhoiRole extends javax.swing.JPanel {

    /**
     * Creates new form JPanelXoaLoginKhoiRole
     */
    public JPanelXoaLoginKhoiRole() {
        initComponents();
        lbThongBaoKhongTonTai.setVisible(false);
        lbRoleHienTai.setVisible(false);
        lbTenRoleHienTai.setVisible(false);
        btnXoaLoginKhoiRole.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXoaLoginKhoiRole = new javax.swing.JButton();
        lbTenRoleHienTai = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lbThongBaoKhongTonTai = new javax.swing.JLabel();
        lbRoleHienTai = new javax.swing.JLabel();

        btnXoaLoginKhoiRole.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaLoginKhoiRole.setText("Xóa Login Khỏi Role");
        btnXoaLoginKhoiRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoginKhoiRoleActionPerformed(evt);
            }
        });

        lbTenRoleHienTai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTenRoleHienTai.setForeground(new java.awt.Color(255, 0, 0));
        lbTenRoleHienTai.setText("Tên Role");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xóa Login Khỏi Role");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Tên đăng nhập: ");

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        lbThongBaoKhongTonTai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbThongBaoKhongTonTai.setForeground(new java.awt.Color(255, 0, 0));
        lbThongBaoKhongTonTai.setText("Tên đăng nhập không tồn tại!");

        lbRoleHienTai.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbRoleHienTai.setText("Role hiện tại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbThongBaoKhongTonTai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbRoleHienTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTenRoleHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaLoginKhoiRole)
                .addGap(392, 392, 392))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbThongBaoKhongTonTai))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRoleHienTai)
                    .addComponent(lbTenRoleHienTai))
                .addGap(45, 45, 45)
                .addComponent(btnXoaLoginKhoiRole, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaLoginKhoiRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoginKhoiRoleActionPerformed
        // TODO add your handling code here:

        String sql = "EXEC sp_droprolemember '" + lbTenRoleHienTai.getText() +"', '" + txtUsername.getText() +"';";
        try {
            Connection con = DataBaseHelper.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            lbTenRoleHienTai.setText("Không thuộc role nào cả!");
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaLoginKhoiRoleActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        // kiểm tra xem có tồn tại tài khoản
        String sql = "SELECT name FROM master.sys.sql_logins WHERE name <> 'sa';";
        try {
            Connection con = DataBaseHelper.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            boolean tonTaiTK = false;
            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase(txtUsername.getText())) {
                    tonTaiTK = true;
                    break;
                }
            }
            if (!tonTaiTK) {
                lbThongBaoKhongTonTai.setVisible(true);
                lbRoleHienTai.setVisible(false);
                btnXoaLoginKhoiRole.setVisible(false);
                lbTenRoleHienTai.setVisible(false);
                return;
            }
            lbThongBaoKhongTonTai.setVisible(false);
            lbRoleHienTai.setVisible(true);
            btnXoaLoginKhoiRole.setVisible(true);
            // lấy role của tài khoản để set vào label tên role hiện tại
            sql = "SELECT name FROM (SELECT name, principal_id FROM sys.database_principals) AS Database_principal_name_id, (SELECT role_principal_id FROM sys.database_role_members ,(SELECT principal_id FROM sys.database_principals WHERE name = '"+ txtUsername.getText() +"') AS id_login WHERE member_principal_id = id_login.principal_id) AS USERNAME_HAS_ROLE " +
            "WHERE USERNAME_HAS_ROLE.role_principal_id = Database_principal_name_id.principal_id";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                lbTenRoleHienTai.setText(rs.getString(1));
            } else {
                lbTenRoleHienTai.setText("Không thuộc role nào cả.");
                lbTenRoleHienTai.setVisible(true);
                btnXoaLoginKhoiRole.setVisible(false);
                return;
            }
            lbTenRoleHienTai.setVisible(true);
            btnXoaLoginKhoiRole.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaLoginKhoiRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbRoleHienTai;
    private javax.swing.JLabel lbTenRoleHienTai;
    private javax.swing.JLabel lbThongBaoKhongTonTai;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
