/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import BACKUP_RESTORE.FormBackUp;
import TTCS.FormCapQuyen;
import com.formdev.flatlaf.FlatIntelliJLaf;
import dao.Provider;
import design.MainQl;
import doan.SetImage;
import quanly.main;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hyipd
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap
     */
    
    
    public DangNhap() {
        initComponents();
        
        try {
            DataBaseHelper.con = DataBaseHelper.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setLocationRelativeTo(null);
        try
        {
            ImageIcon img = new ImageIcon("image//Login.png");
            this.setIconImage(img.getImage());
            new SetImage().setImageLabel(jLabelTtk, "image//user.png");
            new SetImage().setImageLabel(jLabelMk, "image//pass.png");
            new SetImage().setImageButton(jButtonDangNhap, "image//Login-icon.png");
            new SetImage().setImageButton(jButtonThoat, "image//Logout-icon.png");

            
        } catch(Exception ex)
        {
            ex.printStackTrace();
        }
        jTextTenTk.setText("giangvien3");
        jPasswordMK.setText("123456");
        
        try{
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        }catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jTextTenTk = new javax.swing.JTextField();
        jPasswordMK = new javax.swing.JPasswordField();
        jButtonDangNhap = new javax.swing.JButton();
        jLabelMk = new javax.swing.JLabel();
        jLabelTtk = new javax.swing.JLabel();
        jButtonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDangNhap1 = new javax.swing.JButton();
        jButtonDangNhap2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm Sinh Viên");
        setBackground(new java.awt.Color(0, 204, 204));
        setUndecorated(true);

        jTextTenTk.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jPasswordMK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jButtonDangNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDangNhap.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDangNhap.setText("Đăng Nhập");
        jButtonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhapActionPerformed(evt);
            }
        });

        jLabelMk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMk.setText("Mật khẩu:");

        jLabelTtk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTtk.setText("Tên tài khoản:");

        jButtonThoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonThoat.setForeground(new java.awt.Color(255, 0, 51));
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("                        QUẢN LÝ ĐIỂM SINH VIÊN");

        jButtonDangNhap1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDangNhap1.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDangNhap1.setText("PHÂN QUYỀN VÀ TRIGGER");
        jButtonDangNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhap1ActionPerformed(evt);
            }
        });

        jButtonDangNhap2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDangNhap2.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDangNhap2.setText("BACK UP AND RESTORE");
        jButtonDangNhap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhap2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jButtonDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMk)
                                    .addComponent(jLabelTtk))
                                .addGap(34, 34, 34)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextTenTk, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jPasswordMK)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButtonDangNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonDangNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTenTk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTtk, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordMK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDangNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDangNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhapActionPerformed
        // TODO add your handling code here:
        if(jTextTenTk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên tài khoản không được để trống");
            return;
        }
        if(jPasswordMK.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống");
            return;
        }

            String sql1 = "SELECT MaTk,MaVaitro FROM TaiKhoan where" +
                    " tentaikhoan=? and matkhau=CONVERT(VARCHAR(32), HashBytes('MD5', ?), 2)";
           
            try(
            PreparedStatement smt = DataBaseHelper.con.prepareStatement(sql1);   
                    )
            {
                smt.setString(1,jTextTenTk.getText());
                smt.setString(2,jPasswordMK.getText());
      
                ResultSet rs = smt.executeQuery();
               
                if(rs.next()) 
                {   
                    
                    String vaiTro = rs.getString(2);
                    if(vaiTro.equals("VT1"))
                    {
                        new MainQl(rs.getString(1),true).setVisible(true);
                        this.setVisible(false);
                    }
                    else if(vaiTro.equals("VT2"))
                    {
                        Provider.maGv = rs.getString(1);
                        new MainQl(rs.getString(1),false).setVisible(true);                    
                        this.setVisible(false);
                    }
                    else if(vaiTro.equals("VT3"))
                    {
                        new MainSinhVien(rs.getString(1)).setVisible(true);
                        this.setVisible(false);
                    }
                            
                    
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Nhập sai tên tài khoản hoặc mật khẩu");
                    jTextTenTk.grabFocus();
                }
                
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(this, ex.toString());
            }
            
        
       
//        try(
//            PreparedStatement smt =DataBaseHelper.con.prepareStatement(jRadioQl.isSelected() ? sql : sql2 );)
//            {
//                smt.setString(1,jTextTenTk.getText());
//                smt.setString(2,jPasswordMK.getText());
//                ResultSet rs = smt.executeQuery();
//                if(rs.next()) 
//                {
//                    if(jRadioQl.isSelected())
//                    {
//                        new MainQl().setVisible(true);
//                        this.setVisible(false);
//                    }
//                    else
//                    {
//                        new MainSinhVien(jTextTenTk.getText()).setVisible(true);
//                        this.setVisible(false);
//                    }
//                }
//                else
//                {
//JOptionPane.showMessageDialog(this, "Nhap sai ten tai khoan hoac mat khau");                    JOptionPane.showMessageDialog(this, "Nhap sai ten tai khoan hoac mat khau");
//                    jTextTenTk.grabFocus();
//                }
//                
//            } 
//        catch (SQLException ex) 
//        {
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_jButtonDangNhapActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonDangNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhap1ActionPerformed
        // TODO add your handling code here:
            new FormCapQuyen().setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_jButtonDangNhap1ActionPerformed

    private void jButtonDangNhap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhap2ActionPerformed
        // TODO add your handling code here:
        new FormBackUp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDangNhap2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDangNhap;
    private javax.swing.JButton jButtonDangNhap1;
    private javax.swing.JButton jButtonDangNhap2;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMk;
    private javax.swing.JLabel jLabelTtk;
    private javax.swing.JPasswordField jPasswordMK;
    private javax.swing.JTextField jTextTenTk;
    private com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
