/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import com.formdev.flatlaf.FlatIntelliJLaf;
import design.MainQl;
import doan.DataBaseHelper;
import doan.SetImage;
import quanly.main;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import doan.DataBaseHelper;
/**
 *
 * @author hyipd
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap
     */
    public DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        try
        {
            ImageIcon img = new ImageIcon("image//Login.png");
            this.setIconImage(img.getImage());
            new SetImage().setImageLabel(jLabelTtk, "image//user.png");
            new SetImage().setImageLabel(jLabelMk, "image//pass.png");
            new SetImage().setImageButton(jButtonDangNhap, "image//Login-icon.png");
            new SetImage().setImageButton(jButtonThoat, "image//Logout-icon.png");

            
        } catch(Exception ex)
        {
            ex.printStackTrace();
        }
        jTextTenTk.setText("sa");
        jPasswordMK.setText("sa");
        
        try{
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        }catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jTextTenTk = new javax.swing.JTextField();
        jRadioSv = new javax.swing.JRadioButton();
        jPasswordMK = new javax.swing.JPasswordField();
        jButtonDangNhap = new javax.swing.JButton();
        jLabelMk = new javax.swing.JLabel();
        jRadioQl = new javax.swing.JRadioButton();
        jLabelTtk = new javax.swing.JLabel();
        jButtonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm Sinh Viên");
        setBackground(new java.awt.Color(0, 204, 204));
        setUndecorated(true);

        jTextTenTk.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        buttonGroup1.add(jRadioSv);
        jRadioSv.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jRadioSv.setForeground(new java.awt.Color(255, 255, 255));
        jRadioSv.setText("Sinh viên");

        jPasswordMK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jButtonDangNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDangNhap.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDangNhap.setText("Đăng Nhập");
        jButtonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhapActionPerformed(evt);
            }
        });

        jLabelMk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMk.setText("Mật khẩu:");

        buttonGroup1.add(jRadioQl);
        jRadioQl.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jRadioQl.setForeground(new java.awt.Color(255, 255, 255));
        jRadioQl.setSelected(true);
        jRadioQl.setText("Quản lý");

        jLabelTtk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTtk.setText("Tên tài khoản:");

        jButtonThoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonThoat.setForeground(new java.awt.Color(255, 0, 51));
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTtk)
                            .addComponent(jLabelMk))
                        .addGap(34, 34, 34)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTenTk, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordMK, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButtonDangNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jRadioQl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jRadioSv, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTtk)
                    .addComponent(jTextTenTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMk)
                    .addComponent(jPasswordMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioQl)
                    .addComponent(jRadioSv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDangNhap)
                    .addComponent(jButtonThoat))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhapActionPerformed
        // TODO add your handling code here:
        if(jTextTenTk.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Tên tài khoản không được để trống");
            return;
        }
        if(jPasswordMK.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống");
            return;
        }

        
        
        if(jRadioQl.isSelected())
        {   
            DataBaseHelper.name=jTextTenTk.getText();
            DataBaseHelper.pass=jPasswordMK.getText();
            try(Connection con = DataBaseHelper.getConnection();)
            {     
                new MainQl().setVisible(true);
                this.setVisible(false);      
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(this, "Nhập sai tên tài khoản hoặc mật khẩu");
            }
            
        }
        else
        {
            DataBaseHelper.name="DS_SINHVIEN";
            DataBaseHelper.pass="123456";
            String sql2 = "select masv from taikhoansv where tentaikhoan=? and matkhau=CONVERT(VARCHAR(32), HashBytes('MD5', ?), 2)";
            try(Connection con = DataBaseHelper.getConnection();
            PreparedStatement smt = con.prepareStatement(sql2);)
            {
                smt.setString(1,jTextTenTk.getText());
                smt.setString(2,jPasswordMK.getText());
                ResultSet rs = smt.executeQuery();
                if(rs.next()) 
                {      
                     new MainSinhVien(rs.getString(1)).setVisible(true);
                     this.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Nhập sai tên tài khoản hoặc mật khẩu");
                    jTextTenTk.grabFocus();
                }
                
            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
        }
//        try(Connection con = DataBaseHelper.getConnection();
//            PreparedStatement smt = con.prepareStatement(jRadioQl.isSelected() ? sql : sql2 );)
//            {
//                smt.setString(1,jTextTenTk.getText());
//                smt.setString(2,jPasswordMK.getText());
//                ResultSet rs = smt.executeQuery();
//                if(rs.next()) 
//                {
//                    if(jRadioQl.isSelected())
//                    {
//                        new MainQl().setVisible(true);
//                        this.setVisible(false);
//                    }
//                    else
//                    {
//                        new MainSinhVien(jTextTenTk.getText()).setVisible(true);
//                        this.setVisible(false);
//                    }
//                }
//                else
//                {
//                    JOptionPane.showMessageDialog(this, "Nhap sai ten tai khoan hoac mat khau");
//                    jTextTenTk.grabFocus();
//                }
//                
//            } 
//        catch (SQLException ex) 
//        {
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_jButtonDangNhapActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDangNhap;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabelMk;
    private javax.swing.JLabel jLabelTtk;
    private javax.swing.JPasswordField jPasswordMK;
    private javax.swing.JRadioButton jRadioQl;
    private javax.swing.JRadioButton jRadioSv;
    private javax.swing.JTextField jTextTenTk;
    private com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
